# Auto-generated asset pool map
# Source XML: C:\dev\atayeb-assets-explorer\unpacked\assets\Patron.xml
# Generated by: python main.py --cli assets_mapper -t Patron.xml

PATRON_MAP = {
    "PatronCeres": 43594,
    "PatronCernunnos": 50242,
    "PatronEpona": 80861,
    "PatronMars": 80562,
    "PatronMercury": 50311,
    "PatronMinerva": 27900,
    "PatronNeptun": 27899,
}
